// src/utils/mockData.js — Rich mock data with full specifications

export const MOCK_AWS_SERVICES = [
  // ── Compute ──────────────────────────────────────────────────────────────
  { id:'aws-ec2-i001',name:'web-server-prod-1',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'running',health:'healthy',instanceType:'m5.xlarge',vcpu:4,memory:'16 GB',storage:'100 GB EBS gp3',ip:'10.0.1.10',publicIp:'54.21.33.101',vpc:'vpc-0a1b2c3d',subnet:'subnet-111',securityGroups:['sg-web-prod','sg-default'],os:'Amazon Linux 2',cpu:62,memUsage:71,diskUsage:45,networkIn:1240,networkOut:880,cost:174,uptime:'42d 3h',tags:{Environment:'production',Team:'backend',Project:'webapp'},connections:['aws-rds-db001','aws-ec2-i002','aws-alb-lb001']},
  { id:'aws-ec2-i002',name:'web-server-prod-2',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1b',status:'running',health:'healthy',instanceType:'m5.xlarge',vcpu:4,memory:'16 GB',storage:'100 GB EBS gp3',ip:'10.0.1.11',vpc:'vpc-0a1b2c3d',subnet:'subnet-112',securityGroups:['sg-web-prod'],os:'Amazon Linux 2',cpu:58,memUsage:66,diskUsage:42,networkIn:1100,networkOut:790,cost:174,uptime:'42d 3h',tags:{Environment:'production',Team:'backend'},connections:['aws-rds-db001','aws-alb-lb001']},
  { id:'aws-ec2-i003',name:'api-server-staging',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-west-2',az:'us-west-2a',status:'running',health:'warning',instanceType:'t3.large',vcpu:2,memory:'8 GB',storage:'50 GB EBS gp2',ip:'10.1.0.5',vpc:'vpc-staging',subnet:'subnet-201',os:'Ubuntu 22.04',cpu:87,memUsage:82,diskUsage:79,cost:67,uptime:'7d 12h',tags:{Environment:'staging',Team:'api'},connections:['aws-rds-db002','aws-lambda-fn001']},
  { id:'aws-ec2-i004',name:'bastion-host',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'running',health:'healthy',instanceType:'t3.micro',vcpu:2,memory:'1 GB',storage:'8 GB EBS gp3',ip:'10.0.0.5',publicIp:'52.14.11.200',vpc:'vpc-0a1b2c3d',subnet:'subnet-pub',os:'Amazon Linux 2',cpu:3,memUsage:12,diskUsage:18,cost:8.5,uptime:'98d 6h',tags:{Purpose:'bastion',Environment:'production'},connections:['aws-ec2-i001','aws-ec2-i002']},
  { id:'aws-ec2-i005',name:'ml-inference-node',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'running',health:'healthy',instanceType:'g4dn.xlarge',vcpu:4,memory:'16 GB',storage:'125 GB NVMe SSD',ip:'10.0.2.20',vpc:'vpc-0a1b2c3d',subnet:'subnet-115',os:'Deep Learning AMI',cpu:72,memUsage:68,diskUsage:55,networkIn:2800,networkOut:1200,cost:526,uptime:'14d 2h',tags:{Team:'ml',Environment:'production'},connections:['aws-s3-bucket002','aws-lambda-fn002']},
  { id:'aws-ec2-i006',name:'worker-node-batch',type:'EC2 Instance',family:'Compute',provider:'aws',region:'eu-west-1',az:'eu-west-1a',status:'running',health:'healthy',instanceType:'c5.2xlarge',vcpu:8,memory:'16 GB',storage:'100 GB EBS gp3',ip:'10.2.0.10',vpc:'vpc-eu-prod',subnet:'subnet-eu-301',os:'Amazon Linux 2',cpu:44,memUsage:52,diskUsage:33,cost:248,uptime:'21d 9h',tags:{Environment:'production',Team:'data'},connections:['aws-sqs-queue001','aws-s3-bucket002']},
  // ── Databases ────────────────────────────────────────────────────────────
  { id:'aws-rds-db001',name:'postgres-prod-primary',type:'RDS Instance',family:'Database',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'available',health:'healthy',instanceType:'db.r5.xlarge',engine:'PostgreSQL 15.3',storage:'500 GB gp3',multiAZ:true,replicaCount:1,backupRetention:7,cpu:34,connections:87,maxConnections:200,deletionProtection:true,vpc:'vpc-0a1b2c3d',cost:242,uptime:'112d 5h',tags:{Environment:'production',Type:'primary'},connections:['aws-ec2-i001','aws-ec2-i002','aws-lambda-fn001']},
  { id:'aws-rds-db002',name:'mysql-staging',type:'RDS Instance',family:'Database',provider:'aws',region:'us-west-2',az:'us-west-2b',status:'available',health:'healthy',instanceType:'db.t3.medium',engine:'MySQL 8.0',storage:'100 GB gp2',multiAZ:false,replicaCount:0,backupRetention:3,cpu:22,connections:14,maxConnections:100,cost:34,uptime:'18d 2h',tags:{Environment:'staging'},connections:['aws-ec2-i003']},
  { id:'aws-rds-db003',name:'aurora-analytics',type:'Aurora Cluster',family:'Database',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'available',health:'healthy',instanceType:'db.r6g.2xlarge',engine:'Aurora MySQL 3.0',storage:'Auto-scaling',multiAZ:true,replicaCount:2,backupRetention:14,cpu:41,connections:128,maxConnections:300,cost:580,uptime:'65d 4h',tags:{Environment:'production',Type:'analytics'},connections:['aws-lambda-fn002','aws-ec2-i005']},
  // ── Storage ──────────────────────────────────────────────────────────────
  { id:'aws-s3-bucket001',name:'app-assets-production',type:'S3 Bucket',family:'Storage',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',sizeGB:142.8,objects:48320,storageClass:'STANDARD',versioning:true,encryption:'AES-256',cost:3.28,tags:{Environment:'production',Type:'assets'},connections:['aws-ec2-i001','aws-cloudfront-cf001']},
  { id:'aws-s3-bucket002',name:'data-lake-raw',type:'S3 Bucket',family:'Storage',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',sizeGB:2840,objects:1482300,storageClass:'INTELLIGENT_TIERING',versioning:true,encryption:'SSE-KMS',cost:65.32,tags:{Team:'data',Project:'analytics'},connections:['aws-lambda-fn002','aws-ec2-i006']},
  { id:'aws-s3-bucket003',name:'backups-prod',type:'S3 Bucket',family:'Storage',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',sizeGB:8200,objects:320000,storageClass:'GLACIER',versioning:false,encryption:'SSE-KMS',cost:18.44,tags:{Type:'backups',RetentionPolicy:'7years'},connections:[]},
  // ── Serverless ───────────────────────────────────────────────────────────
  { id:'aws-lambda-fn001',name:'user-auth-handler',type:'Lambda Function',family:'Serverless',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',runtime:'nodejs20.x',memorySize:'256 MB',timeout:30,invocations:284200,errors:12,duration:87,throttles:0,cost:0.98,tags:{Team:'backend',Service:'auth'},connections:['aws-rds-db001','aws-s3-bucket001']},
  { id:'aws-lambda-fn002',name:'data-processor',type:'Lambda Function',family:'Serverless',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',runtime:'python3.12',memorySize:'1024 MB',timeout:300,invocations:52840,errors:3,duration:4200,throttles:2,cost:2.14,tags:{Team:'data'},connections:['aws-s3-bucket002','aws-rds-db001']},
  { id:'aws-lambda-fn003',name:'event-transformer',type:'Lambda Function',family:'Serverless',provider:'aws',region:'eu-west-1',status:'Active',health:'healthy',runtime:'python3.12',memorySize:'512 MB',timeout:60,invocations:128400,errors:0,duration:210,throttles:0,cost:1.44,tags:{Team:'events'},connections:['aws-sqs-queue001']},
  // ── Containers ───────────────────────────────────────────────────────────
  { id:'aws-eks-cluster001',name:'prod-k8s-cluster',type:'EKS Cluster',family:'Container',provider:'aws',region:'us-east-1',status:'ACTIVE',health:'healthy',kubernetesVersion:'1.29',nodes:8,nodeGroups:3,nodeType:'m5.large',pods:128,runningPods:124,cpu:48,memUsage:61,vpc:'vpc-0a1b2c3d',cost:800,uptime:'89d 4h',tags:{Environment:'production',Team:'platform'},connections:['aws-rds-db001','aws-elasticache-001','aws-alb-lb001']},
  { id:'aws-eks-cluster002',name:'staging-k8s-cluster',type:'EKS Cluster',family:'Container',provider:'aws',region:'us-west-2',status:'ACTIVE',health:'warning',kubernetesVersion:'1.28',nodes:3,nodeGroups:1,nodeType:'t3.medium',pods:42,runningPods:38,cpu:71,memUsage:78,vpc:'vpc-staging',cost:290,uptime:'12d 6h',tags:{Environment:'staging',Team:'platform'},connections:['aws-rds-db002']},
  // ── Cache ────────────────────────────────────────────────────────────────
  { id:'aws-elasticache-001',name:'redis-session-cache',type:'ElastiCache Cluster',family:'Cache',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'available',health:'healthy',engine:'Redis 7.0',instanceType:'cache.r6g.large',numNodes:3,cpu:18,cost:142,tags:{Service:'sessions'},connections:['aws-ec2-i001','aws-ec2-i002','aws-eks-cluster001']},
  // ── Networking ───────────────────────────────────────────────────────────
  { id:'aws-alb-lb001',name:'prod-application-lb',type:'ALB Load Balancer',family:'Networking',provider:'aws',region:'us-east-1',status:'active',health:'healthy',scheme:'internet-facing',dnsName:'prod-alb-1234567890.us-east-1.elb.amazonaws.com',vpc:'vpc-0a1b2c3d',ipAddressType:'ipv4',cost:28,tags:{Environment:'production'},connections:['aws-ec2-i001','aws-ec2-i002','aws-eks-cluster001']},
  { id:'aws-vpc-001',name:'vpc-production',type:'VPC',family:'Networking',provider:'aws',region:'us-east-1',status:'available',health:'healthy',cidr:'10.0.0.0/16',subnets:8,routeTables:4,natGateways:2,cost:0,tags:{Environment:'production'},connections:['aws-ec2-i001','aws-ec2-i002','aws-rds-db001']},
  // ── CDN ──────────────────────────────────────────────────────────────────
  { id:'aws-cloudfront-cf001',name:'cdn-distribution',type:'CloudFront Distribution',family:'CDN',provider:'aws',region:'Global',status:'Deployed',health:'healthy',origins:2,behaviors:4,cost:18,tags:{},connections:['aws-s3-bucket001','aws-alb-lb001']},
  // ── Messaging ────────────────────────────────────────────────────────────
  { id:'aws-sqs-queue001',name:'order-processing-queue',type:'SQS Queue',family:'Messaging',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',messages:842,messagesInFlight:23,isFifo:false,cost:1.2,tags:{Team:'orders'},connections:['aws-lambda-fn001','aws-ec2-i001']},
  { id:'aws-sqs-queue002',name:'notification-queue-fifo',type:'SQS Queue',family:'Messaging',provider:'aws',region:'us-east-1',status:'Active',health:'healthy',messages:241,messagesInFlight:8,isFifo:true,cost:0.6,tags:{Team:'notifications'},connections:['aws-lambda-fn003']},
  // ── Stopped / Private instances ────────────────────────────────────────
  { id:'aws-ec2-i007',name:'dev-server-stopped',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'stopped',health:'critical',instanceType:'t3.medium',vcpu:2,memory:'4 GB',storage:'50 GB EBS gp2',ip:'10.0.3.20',vpc:'vpc-0a1b2c3d',subnet:'subnet-113',os:'Ubuntu 20.04',cpu:0,memUsage:0,cost:0,uptime:'0d',isPrivate:true,networkAccess:'private',tags:{Environment:'development',Team:'dev'},connections:[]},
  { id:'aws-ec2-i008',name:'legacy-app-server',type:'EC2 Instance',family:'Compute',provider:'aws',region:'us-east-1',az:'us-east-1b',status:'stopped',health:'critical',instanceType:'m5.large',vcpu:2,memory:'8 GB',storage:'80 GB EBS gp2',ip:'10.0.3.21',vpc:'vpc-0a1b2c3d',subnet:'subnet-114',os:'Amazon Linux 2',cpu:0,memUsage:0,cost:0,uptime:'0d',isPrivate:true,networkAccess:'private',tags:{Environment:'production',Status:'decommissioned'},connections:[]},
  { id:'aws-rds-db004',name:'analytics-db-private',type:'RDS Instance',family:'Database',provider:'aws',region:'us-east-1',az:'us-east-1a',status:'available',health:'healthy',instanceType:'db.r5.large',engine:'PostgreSQL 14',storage:'200 GB gp2',multiAZ:false,cpu:18,connections:5,isPrivate:true,networkAccess:'private',publiclyAccessible:false,vpc:'vpc-0a1b2c3d',cost:121,uptime:'44d',tags:{Environment:'production',Access:'internal-only'},connections:['aws-ec2-i001']},
];

export const MOCK_GCP_SERVICES = [
  // ── Compute ──────────────────────────────────────────────────────────────
  { id:'gcp-compute-vm001',name:'api-server-1',type:'Compute Engine VM',family:'Compute',provider:'gcp',region:'us-central1',zone:'us-central1-a',status:'RUNNING',health:'healthy',machineType:'n2-standard-4',vcpu:4,memory:'16 GB',storage:'50 GB SSD',cpu:44,memUsage:58,diskUsage:38,ip:'10.128.0.2',publicIp:'35.222.11.45',network:'default',subnetwork:'default',os:'Debian 11',cost:96,uptime:'35d 8h',tags:{env:'production',tier:'api'},connections:['gcp-sql-db001','gcp-gke-cluster001','gcp-memorystore-001']},
  { id:'gcp-compute-vm002',name:'worker-node-1',type:'Compute Engine VM',family:'Compute',provider:'gcp',region:'us-central1',zone:'us-central1-b',status:'RUNNING',health:'warning',machineType:'n1-standard-2',vcpu:2,memory:'7.5 GB',storage:'30 GB SSD',cpu:88,memUsage:91,diskUsage:72,ip:'10.128.0.3',network:'default',os:'Ubuntu 20.04',cost:48,uptime:'12d 6h',tags:{env:'production',role:'worker'},connections:['gcp-pubsub-001','gcp-sql-db001']},
  { id:'gcp-compute-vm003',name:'batch-processor-eu',type:'Compute Engine VM',family:'Compute',provider:'gcp',region:'europe-west1',zone:'europe-west1-b',status:'RUNNING',health:'healthy',machineType:'n2-standard-8',vcpu:8,memory:'32 GB',storage:'200 GB SSD',cpu:56,memUsage:48,diskUsage:40,ip:'10.132.0.5',network:'eu-network',os:'CentOS 7',cost:192,uptime:'44d 11h',tags:{env:'production',team:'data'},connections:['gcp-bigquery-ds001','gcp-gcs-bucket002']},
  // ── Containers ───────────────────────────────────────────────────────────
  { id:'gcp-gke-cluster001',name:'prod-gke-cluster',type:'GKE Cluster',family:'Container',provider:'gcp',region:'us-central1',zone:'us-central1-a',status:'RUNNING',health:'healthy',kubernetesVersion:'1.28.7-gke',nodes:6,nodeType:'n2-standard-4',pods:96,runningPods:94,cpu:52,memUsage:64,network:'default',cost:576,uptime:'71d 3h',tags:{env:'production',team:'platform'},connections:['gcp-sql-db001','gcp-memorystore-001','gcp-gcs-bucket001']},
  { id:'gcp-gke-cluster002',name:'ml-workloads-gke',type:'GKE Cluster',family:'Container',provider:'gcp',region:'us-central1',zone:'us-central1-c',status:'RUNNING',health:'healthy',kubernetesVersion:'1.29.2-gke',nodes:4,nodeType:'n1-highmem-8',pods:24,runningPods:24,cpu:34,memUsage:72,network:'ml-network',cost:780,uptime:'28d 4h',tags:{env:'production',team:'ml'},connections:['gcp-gcs-bucket001','gcp-bigquery-ds001']},
  // ── Databases ────────────────────────────────────────────────────────────
  { id:'gcp-sql-db001',name:'postgres-main',type:'Cloud SQL Instance',family:'Database',provider:'gcp',region:'us-central1',zone:'us-central1-a',status:'RUNNABLE',health:'healthy',engine:'POSTGRES_15',tier:'db-n1-standard-4',storage:'200 GB SSD',multiAZ:true,backupEnabled:true,cpu:28,connections:42,maxConnections:100,cost:280,uptime:'71d 3h',tags:{env:'production',type:'primary'},connections:['gcp-compute-vm001','gcp-gke-cluster001','gcp-function-fn001']},
  { id:'gcp-sql-db002',name:'mysql-replica-eu',type:'Cloud SQL Instance',family:'Database',provider:'gcp',region:'europe-west1',zone:'europe-west1-b',status:'RUNNABLE',health:'healthy',engine:'MYSQL_8_0',tier:'db-n1-standard-2',storage:'100 GB SSD',multiAZ:false,backupEnabled:true,cpu:15,connections:28,maxConnections:100,cost:120,uptime:'44d 11h',tags:{env:'production',type:'replica'},connections:['gcp-compute-vm003']},
  // ── Storage ──────────────────────────────────────────────────────────────
  { id:'gcp-gcs-bucket001',name:'media-storage-prod',type:'Cloud Storage Bucket',family:'Storage',provider:'gcp',region:'us',status:'Active',health:'healthy',storageClass:'STANDARD',sizeGB:380,objects:124000,versioning:true,encryption:'Google-managed',cost:8.74,tags:{env:'production',type:'media'},connections:['gcp-function-fn001','gcp-gke-cluster001']},
  { id:'gcp-gcs-bucket002',name:'backup-archive',type:'Cloud Storage Bucket',family:'Storage',provider:'gcp',region:'us',status:'Active',health:'healthy',storageClass:'NEARLINE',sizeGB:2200,objects:840000,versioning:false,encryption:'Google-managed',cost:22.0,tags:{type:'backups'},connections:['gcp-compute-vm003']},
  // ── Serverless ───────────────────────────────────────────────────────────
  { id:'gcp-function-fn001',name:'image-resizer',type:'Cloud Function',family:'Serverless',provider:'gcp',region:'us-central1',status:'ACTIVE',health:'healthy',runtime:'nodejs20',memorySize:'512 MB',timeout:'60',invocations:198400,errors:4,duration:142,cost:0.76,tags:{team:'media'},connections:['gcp-gcs-bucket001','gcp-sql-db001']},
  { id:'gcp-function-fn002',name:'auth-webhook',type:'Cloud Function',family:'Serverless',provider:'gcp',region:'us-central1',status:'ACTIVE',health:'healthy',runtime:'python311',memorySize:'256 MB',timeout:'30',invocations:88200,errors:1,duration:68,cost:0.32,tags:{team:'backend'},connections:['gcp-sql-db001']},
  // ── Analytics ────────────────────────────────────────────────────────────
  { id:'gcp-bigquery-ds001',name:'analytics-warehouse',type:'BigQuery Dataset',family:'Analytics',provider:'gcp',region:'us',status:'Active',health:'healthy',tableCount:142,cost:48.2,tags:{team:'data',env:'production'},connections:['gcp-gcs-bucket002','gcp-compute-vm003']},
  // ── Messaging ────────────────────────────────────────────────────────────
  { id:'gcp-pubsub-001',name:'events-topic',type:'Pub/Sub Topic',family:'Messaging',provider:'gcp',region:'global',status:'Active',health:'healthy',messages:12400,subscriptions:3,cost:1.8,tags:{team:'backend'},connections:['gcp-compute-vm002','gcp-function-fn001']},
  // ── Cache ────────────────────────────────────────────────────────────────
  { id:'gcp-memorystore-001',name:'redis-cache',type:'Cloud Memorystore',family:'Cache',provider:'gcp',region:'us-central1',zone:'us-central1-a',status:'READY',health:'healthy',engine:'Redis 7.0',tier:'STANDARD_HA',memorySizeGb:5,cpu:22,cost:88,tags:{service:'cache'},connections:['gcp-compute-vm001','gcp-gke-cluster001']},
  // ── Networking ───────────────────────────────────────────────────────────
  { id:'gcp-vpc-001',name:'production-vpc',type:'VPC Network',family:'Networking',provider:'gcp',region:'global',status:'Active',health:'healthy',subnets:6,firewallRules:12,routes:8,cost:0,tags:{env:'production'},connections:['gcp-compute-vm001','gcp-gke-cluster001']},
];

export const MOCK_AZURE_SERVICES = [
  // ── Compute ──────────────────────────────────────────────────────────────
  { id:'az-vm-vm001',name:'app-server-eastus-1',type:'Virtual Machine',family:'Compute',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'running',health:'healthy',size:'Standard_D4s_v3',vcpu:4,memory:'16 GB',storage:'128 GB Premium SSD',os:'Linux',cpu:55,memUsage:68,diskUsage:44,cost:140,uptime:'28d 9h',tags:{environment:'production',tier:'web'},connections:['az-sqldb-db001','az-aks-aks001','az-redis-001']},
  { id:'az-vm-vm002',name:'app-server-eastus-2',type:'Virtual Machine',family:'Compute',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'running',health:'warning',size:'Standard_D4s_v3',vcpu:4,memory:'16 GB',storage:'128 GB Premium SSD',os:'Linux',cpu:91,memUsage:87,diskUsage:83,cost:140,uptime:'28d 9h',tags:{environment:'production',tier:'web'},connections:['az-sqldb-db001','az-aks-aks001']},
  { id:'az-vm-vm003',name:'dev-build-server',type:'Virtual Machine',family:'Compute',provider:'azure',region:'westeurope',resourceGroup:'rg-dev',status:'running',health:'healthy',size:'Standard_B4ms',vcpu:4,memory:'16 GB',storage:'64 GB Standard SSD',os:'Windows Server 2022',cpu:34,memUsage:55,diskUsage:62,cost:72,uptime:'5d 3h',tags:{environment:'development',team:'devops'},connections:[]},
  // ── Containers ───────────────────────────────────────────────────────────
  { id:'az-aks-aks001',name:'prod-aks-cluster',type:'AKS Cluster',family:'Container',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',kubernetesVersion:'1.28.5',nodes:10,nodeGroups:2,nodeType:'Standard_D4s_v3',pods:128,runningPods:126,cpu:49,memUsage:63,cost:1000,uptime:'60d 2h',tags:{environment:'production',team:'platform'},connections:['az-sqldb-db001','az-cosmos-db001','az-eventhub-ns001']},
  { id:'az-aks-aks002',name:'batch-aks-westeu',type:'AKS Cluster',family:'Container',provider:'azure',region:'westeurope',resourceGroup:'rg-westeu',status:'Succeeded',health:'healthy',kubernetesVersion:'1.28.5',nodes:4,nodeGroups:1,nodeType:'Standard_D2s_v3',pods:38,runningPods:38,cpu:31,memUsage:44,cost:350,uptime:'32d 7h',tags:{environment:'production',team:'data'},connections:['az-storage-sa001']},
  // ── Databases ────────────────────────────────────────────────────────────
  { id:'az-sqldb-db001',name:'sqldb-webapp',type:'Azure SQL Database',family:'Database',provider:'azure',region:'eastus',resourceGroup:'rg-production',server:'sql-server-prod',status:'Online',health:'healthy',tier:'GeneralPurpose',size:'GP_Gen5_4',storageGB:256,cpu:31,connections:54,maxConnections:200,geoReplication:true,cost:368,uptime:'60d 2h',tags:{environment:'production',type:'primary'},connections:['az-vm-vm001','az-vm-vm002','az-aks-aks001']},
  { id:'az-cosmos-db001',name:'cosmos-userdata',type:'Cosmos DB Account',family:'Database',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',kind:'GlobalDocumentDB',geoReplication:true,writeLocations:1,readLocations:2,cpu:22,connections:38,cost:182,uptime:'60d 2h',tags:{environment:'production',team:'backend'},connections:['az-aks-aks001','az-func-fn001']},
  { id:'az-mysql-db001',name:'mysql-db-westeu',type:'Azure Database for MySQL',family:'Database',provider:'azure',region:'westeurope',resourceGroup:'rg-westeu',status:'Online',health:'healthy',tier:'GeneralPurpose',size:'GP_Gen5_2',storageGB:128,cpu:18,connections:22,maxConnections:100,cost:140,uptime:'32d 7h',tags:{environment:'production',team:'web'},connections:['az-vm-vm003','az-aks-aks002']},
  // ── Storage ──────────────────────────────────────────────────────────────
  { id:'az-storage-sa001',name:'blobstorageprod01',type:'Storage Account',family:'Storage',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',tier:'Standard',kind:'StorageV2',accessTier:'Hot',encryption:'Enabled',sizeGB:480,blobCount:92000,cost:9.6,tags:{environment:'production'},connections:['az-func-fn001','az-aks-aks001']},
  { id:'az-storage-sa002',name:'archivestorage-cold',type:'Storage Account',family:'Storage',provider:'azure',region:'eastus',resourceGroup:'rg-backups',status:'Succeeded',health:'healthy',tier:'Standard',kind:'StorageV2',accessTier:'Archive',encryption:'Enabled',sizeGB:12400,blobCount:480000,cost:24.8,tags:{type:'archive'},connections:[]},
  // ── Serverless ───────────────────────────────────────────────────────────
  { id:'az-func-fn001',name:'webhook-processor',type:'Azure Function App',family:'Serverless',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Running',health:'healthy',runtime:'node|18',invocations:48200,errors:7,duration:112,cost:1.4,tags:{team:'backend'},connections:['az-cosmos-db001','az-storage-sa001','az-eventhub-ns001']},
  { id:'az-func-fn002',name:'report-generator',type:'Azure Function App',family:'Serverless',provider:'azure',region:'westeurope',resourceGroup:'rg-westeu',status:'Running',health:'healthy',runtime:'python|3.10',invocations:12800,errors:0,duration:4200,cost:0.86,tags:{team:'data'},connections:['az-mysql-db001','az-storage-sa002']},
  // ── Messaging ────────────────────────────────────────────────────────────
  { id:'az-eventhub-ns001',name:'events-namespace-prod',type:'Event Hub Namespace',family:'Messaging',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',tier:'Standard',capacity:2,throughputUnits:10,cost:22,tags:{environment:'production'},connections:['az-aks-aks001','az-func-fn001']},
  { id:'az-servicebus-001',name:'servicebus-prod',type:'Service Bus Namespace',family:'Messaging',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',tier:'Premium',queues:8,topics:4,cost:68,tags:{environment:'production',team:'backend'},connections:['az-func-fn001','az-aks-aks001']},
  // ── Cache ────────────────────────────────────────────────────────────────
  { id:'az-redis-001',name:'redis-cache-prod',type:'Azure Cache for Redis',family:'Cache',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',tier:'Premium',memorySizeGb:13,cpu:28,cost:95,tags:{service:'cache'},connections:['az-vm-vm001','az-aks-aks001']},
  // ── Networking ───────────────────────────────────────────────────────────
  { id:'az-vnet-vnet001',name:'prod-vnet-eastus',type:'Virtual Network',family:'Networking',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',cidr:'10.0.0.0/16',subnets:6,cost:0,tags:{environment:'production'},connections:['az-vm-vm001','az-vm-vm002','az-aks-aks001']},
  { id:'az-appgw-001',name:'app-gateway-prod',type:'Application Gateway',family:'Networking',provider:'azure',region:'eastus',resourceGroup:'rg-production',status:'Succeeded',health:'healthy',tier:'WAF_v2',capacity:'Autoscale',backendPools:3,cost:320,tags:{environment:'production'},connections:['az-vm-vm001','az-aks-aks001']},
];

export const MOCK_ALERTS = [
  { id:'alert-001',title:'High CPU on api-server-staging',message:'CPU utilization at 87% for 15+ minutes — threshold is 80%',severity:'warning',provider:'aws',service:'api-server-staging',region:'us-west-2',time:'5m ago',acknowledged:false },
  { id:'alert-002',title:'Memory Critical on worker-node-1',message:'GCP VM worker-node-1 memory usage at 91% — approaching OOM',severity:'critical',provider:'gcp',service:'worker-node-1',region:'us-central1',time:'12m ago',acknowledged:false },
  { id:'alert-003',title:'High CPU on app-server-eastus-2',message:'Azure VM CPU at 91% — auto-scaling rule triggered',severity:'critical',provider:'azure',service:'app-server-eastus-2',region:'eastus',time:'18m ago',acknowledged:false },
  { id:'alert-004',title:'Disk usage warning on worker-node-1',message:'Root disk at 72% capacity — recommend cleanup',severity:'warning',provider:'gcp',service:'worker-node-1',region:'us-central1',time:'1h ago',acknowledged:false },
  { id:'alert-005',title:'RDS connection pool high',message:'postgres-prod-primary: 87/200 connections used (43%)',severity:'info',provider:'aws',service:'postgres-prod-primary',region:'us-east-1',time:'2h ago',acknowledged:true },
  { id:'alert-006',title:'Lambda error rate elevated',message:'data-processor: 3 errors in last 10 minutes',severity:'warning',provider:'aws',service:'data-processor',region:'us-east-1',time:'3h ago',acknowledged:false },
  { id:'alert-007',title:'Azure SQL DTU high',message:'sqldb-webapp: DTU consumption at 78% for 30 minutes',severity:'warning',provider:'azure',service:'sqldb-webapp',region:'eastus',time:'4h ago',acknowledged:true },
  { id:'alert-008',title:'EKS pod crash loop detected',message:'2 pods in prod-k8s-cluster are in CrashLoopBackOff state',severity:'critical',provider:'aws',service:'prod-k8s-cluster',region:'us-east-1',time:'45m ago',acknowledged:false },
  { id:'alert-009',title:'GKE node auto-scaling triggered',message:'ml-workloads-gke added 2 nodes due to resource pressure',severity:'info',provider:'gcp',service:'ml-workloads-gke',region:'us-central1',time:'1h 20m ago',acknowledged:false },
  { id:'alert-010',title:'Storage account near capacity',message:'archivestorage-cold at 94% of provisioned capacity',severity:'warning',provider:'azure',service:'archivestorage-cold',region:'eastus',time:'6h ago',acknowledged:false },
];

export const NETWORK_NODES = {
  aws: MOCK_AWS_SERVICES.map(s => ({
    id: s.id, label: s.name, type: s.type, family: s.family,
    provider: 'aws', region: s.region, health: s.health, connections: s.connections,
  })),
  gcp: MOCK_GCP_SERVICES.map(s => ({
    id: s.id, label: s.name, type: s.type, family: s.family,
    provider: 'gcp', region: s.region, health: s.health, connections: s.connections,
  })),
  azure: MOCK_AZURE_SERVICES.map(s => ({
    id: s.id, label: s.name, type: s.type, family: s.family,
    provider: 'azure', region: s.region, health: s.health, connections: s.connections,
  })),
};

export const OVERVIEW_STATS = {
  totalServices: MOCK_AWS_SERVICES.length + MOCK_GCP_SERVICES.length + MOCK_AZURE_SERVICES.length,
  healthyServices: [...MOCK_AWS_SERVICES, ...MOCK_GCP_SERVICES, ...MOCK_AZURE_SERVICES].filter(s => s.health === 'healthy').length,
  warningServices: [...MOCK_AWS_SERVICES, ...MOCK_GCP_SERVICES, ...MOCK_AZURE_SERVICES].filter(s => s.health === 'warning').length,
  criticalServices: [...MOCK_AWS_SERVICES, ...MOCK_GCP_SERVICES, ...MOCK_AZURE_SERVICES].filter(s => s.health === 'critical').length,
  totalCostMTD: Math.round([...MOCK_AWS_SERVICES, ...MOCK_GCP_SERVICES, ...MOCK_AZURE_SERVICES].reduce((a, s) => a + (s.cost || 0), 0)),
  regions: 8,
};
